<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 /Users/venco/Projects/nexus/static/models/Nothing3aCommunity.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001: THREE.Mesh
      FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_1: THREE.Mesh
      FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_2: THREE.Mesh
      FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_3: THREE.Mesh
      FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_4: THREE.Mesh
      FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_5: THREE.Mesh
      FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_6: THREE.Mesh
      FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_7: THREE.Mesh
    }
    materials: {
      ['Emission.001']: THREE.MeshStandardMaterial
      CommunityPhoneOpacity: THREE.MeshStandardMaterial
      CommunityPhoneDecal: THREE.MeshStandardMaterial
      CommunityPhoneCameraUnit: THREE.MeshStandardMaterial
      CommunityPhoneLogo: THREE.MeshStandardMaterial
      CommunityPhone: THREE.MeshStandardMaterial
      CommunityPhoneScreen: THREE.MeshStandardMaterial
      CommunityPhoneOpacityCamera: THREE.MeshStandardMaterial
    }
  }

  const dracoLoader = useDraco('https://www.gstatic.com/draco/versioned/decoders/1.5.7/')
  const gltf = useGltf<GLTFResult>('/models/Nothing3aCommunity.glb', { dracoLoader })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[-0.47, 12.93, 0.3]}
      scale={0.96}
    >
      <T.Mesh
        geometry={gltf.nodes.FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001.geometry}
        material={gltf.materials['Emission.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_1.geometry}
        material={gltf.materials.CommunityPhoneOpacity}
      />
      <T.Mesh
        geometry={gltf.nodes.FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_2.geometry}
        material={gltf.materials.CommunityPhoneDecal}
      />
      <T.Mesh
        geometry={gltf.nodes.FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_3.geometry}
        material={gltf.materials.CommunityPhoneCameraUnit}
      />
      <T.Mesh
        geometry={gltf.nodes.FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_4.geometry}
        material={gltf.materials.CommunityPhoneLogo}
      />
      <T.Mesh
        geometry={gltf.nodes.FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_5.geometry}
        material={gltf.materials.CommunityPhone}
      />
      <T.Mesh
        geometry={gltf.nodes.FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_6.geometry}
        material={gltf.materials.CommunityPhoneScreen}
      />
      <T.Mesh
        geometry={gltf.nodes.FBXASC0482_24111_SCREW_M1_4X3_9XT0_75_ncl1_1Shape001_7.geometry}
        material={gltf.materials.CommunityPhoneOpacityCamera}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {#if ref}
    {@render children?.({ ref })}
  {/if}
</T.Group>
