<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 /Users/venco/Projects/nexus/static/models/P8P.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      deviceback: THREE.Mesh
      devicebody_1: THREE.Mesh
      devicebody_2: THREE.Mesh
      devicecamera: THREE.Mesh
      devicecameraglass: THREE.Mesh
      devicelogo: THREE.Mesh
      devicescreen: THREE.Mesh
    }
    materials: {
      ['material.back']: THREE.MeshStandardMaterial
      ['material.body']: THREE.MeshStandardMaterial
      ['material.body.cameraframe']: THREE.MeshStandardMaterial
      ['material.camera']: THREE.MeshStandardMaterial
      ['material.camera.glass']: THREE.MeshStandardMaterial
      ['material.logo']: THREE.MeshStandardMaterial
      ['material.screen']: THREE.MeshStandardMaterial
    }
  }

  const dracoLoader = useDraco('https://www.gstatic.com/draco/versioned/decoders/1.5.7/')
  const gltf = useGltf<GLTFResult>('/models/P8P.glb', { dracoLoader })

</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group scale={0.94}>
      <T.Mesh
        geometry={gltf.nodes.deviceback.geometry}
        material={gltf.materials['material.back']}
      />
      <T.Mesh
        geometry={gltf.nodes.devicecamera.geometry}
        material={gltf.materials['material.camera']}
      />
      <T.Mesh
        geometry={gltf.nodes.devicecameraglass.geometry}
        material={gltf.materials['material.camera.glass']}
      />
      <T.Mesh
        geometry={gltf.nodes.devicelogo.geometry}
        material={gltf.materials['material.logo']}
      />
      <T.Mesh
        geometry={gltf.nodes.devicescreen.geometry}
        material={gltf.materials['material.screen']}
      />
      <T.Mesh
        geometry={gltf.nodes.devicebody_1.geometry}
        material={gltf.materials['material.body']}
      />
      <T.Mesh
        geometry={gltf.nodes.devicebody_2.geometry}
        material={gltf.materials['material.body.cameraframe']}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {#if ref}
    {@render children?.({ ref })}
  {/if}
</T.Group>
